//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gen2_3Capas.ServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWeb.WSRutasSoap")]
    public interface WSRutasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Calle del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insDireccion", ReplyAction="*")]
        Gen2_3Capas.ServicioWeb.insDireccionResponse insDireccion(Gen2_3Capas.ServicioWeb.insDireccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insDireccion", ReplyAction="*")]
        System.Threading.Tasks.Task<Gen2_3Capas.ServicioWeb.insDireccionResponse> insDireccionAsync(Gen2_3Capas.ServicioWeb.insDireccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Descripcion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCargamento", ReplyAction="*")]
        Gen2_3Capas.ServicioWeb.InsertarCargamentoResponse InsertarCargamento(Gen2_3Capas.ServicioWeb.InsertarCargamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCargamento", ReplyAction="*")]
        System.Threading.Tasks.Task<Gen2_3Capas.ServicioWeb.InsertarCargamentoResponse> InsertarCargamentoAsync(Gen2_3Capas.ServicioWeb.InsertarCargamentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insDireccion", Namespace="http://tempuri.org/", Order=0)]
        public Gen2_3Capas.ServicioWeb.insDireccionRequestBody Body;
        
        public insDireccionRequest() {
        }
        
        public insDireccionRequest(Gen2_3Capas.ServicioWeb.insDireccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insDireccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Calle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Colonia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CP;
        
        public insDireccionRequestBody() {
        }
        
        public insDireccionRequestBody(string Calle, string Numero, string Colonia, string Ciudad, string Estado, string CP) {
            this.Calle = Calle;
            this.Numero = Numero;
            this.Colonia = Colonia;
            this.Ciudad = Ciudad;
            this.Estado = Estado;
            this.CP = CP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insDireccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gen2_3Capas.ServicioWeb.insDireccionResponseBody Body;
        
        public insDireccionResponse() {
        }
        
        public insDireccionResponse(Gen2_3Capas.ServicioWeb.insDireccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insDireccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insDireccionResult;
        
        public insDireccionResponseBody() {
        }
        
        public insDireccionResponseBody(int insDireccionResult) {
            this.insDireccionResult = insDireccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCargamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCargamento", Namespace="http://tempuri.org/", Order=0)]
        public Gen2_3Capas.ServicioWeb.InsertarCargamentoRequestBody Body;
        
        public InsertarCargamentoRequest() {
        }
        
        public InsertarCargamentoRequest(Gen2_3Capas.ServicioWeb.InsertarCargamentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCargamentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long IdRuta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Peso;
        
        public InsertarCargamentoRequestBody() {
        }
        
        public InsertarCargamentoRequestBody(long IdRuta, string Descripcion, double Peso) {
            this.IdRuta = IdRuta;
            this.Descripcion = Descripcion;
            this.Peso = Peso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCargamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCargamentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gen2_3Capas.ServicioWeb.InsertarCargamentoResponseBody Body;
        
        public InsertarCargamentoResponse() {
        }
        
        public InsertarCargamentoResponse(Gen2_3Capas.ServicioWeb.InsertarCargamentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCargamentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarCargamentoResult;
        
        public InsertarCargamentoResponseBody() {
        }
        
        public InsertarCargamentoResponseBody(string InsertarCargamentoResult) {
            this.InsertarCargamentoResult = InsertarCargamentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSRutasSoapChannel : Gen2_3Capas.ServicioWeb.WSRutasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSRutasSoapClient : System.ServiceModel.ClientBase<Gen2_3Capas.ServicioWeb.WSRutasSoap>, Gen2_3Capas.ServicioWeb.WSRutasSoap {
        
        public WSRutasSoapClient() {
        }
        
        public WSRutasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSRutasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRutasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRutasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gen2_3Capas.ServicioWeb.insDireccionResponse Gen2_3Capas.ServicioWeb.WSRutasSoap.insDireccion(Gen2_3Capas.ServicioWeb.insDireccionRequest request) {
            return base.Channel.insDireccion(request);
        }
        
        public int insDireccion(string Calle, string Numero, string Colonia, string Ciudad, string Estado, string CP) {
            Gen2_3Capas.ServicioWeb.insDireccionRequest inValue = new Gen2_3Capas.ServicioWeb.insDireccionRequest();
            inValue.Body = new Gen2_3Capas.ServicioWeb.insDireccionRequestBody();
            inValue.Body.Calle = Calle;
            inValue.Body.Numero = Numero;
            inValue.Body.Colonia = Colonia;
            inValue.Body.Ciudad = Ciudad;
            inValue.Body.Estado = Estado;
            inValue.Body.CP = CP;
            Gen2_3Capas.ServicioWeb.insDireccionResponse retVal = ((Gen2_3Capas.ServicioWeb.WSRutasSoap)(this)).insDireccion(inValue);
            return retVal.Body.insDireccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gen2_3Capas.ServicioWeb.insDireccionResponse> Gen2_3Capas.ServicioWeb.WSRutasSoap.insDireccionAsync(Gen2_3Capas.ServicioWeb.insDireccionRequest request) {
            return base.Channel.insDireccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gen2_3Capas.ServicioWeb.insDireccionResponse> insDireccionAsync(string Calle, string Numero, string Colonia, string Ciudad, string Estado, string CP) {
            Gen2_3Capas.ServicioWeb.insDireccionRequest inValue = new Gen2_3Capas.ServicioWeb.insDireccionRequest();
            inValue.Body = new Gen2_3Capas.ServicioWeb.insDireccionRequestBody();
            inValue.Body.Calle = Calle;
            inValue.Body.Numero = Numero;
            inValue.Body.Colonia = Colonia;
            inValue.Body.Ciudad = Ciudad;
            inValue.Body.Estado = Estado;
            inValue.Body.CP = CP;
            return ((Gen2_3Capas.ServicioWeb.WSRutasSoap)(this)).insDireccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gen2_3Capas.ServicioWeb.InsertarCargamentoResponse Gen2_3Capas.ServicioWeb.WSRutasSoap.InsertarCargamento(Gen2_3Capas.ServicioWeb.InsertarCargamentoRequest request) {
            return base.Channel.InsertarCargamento(request);
        }
        
        public string InsertarCargamento(long IdRuta, string Descripcion, double Peso) {
            Gen2_3Capas.ServicioWeb.InsertarCargamentoRequest inValue = new Gen2_3Capas.ServicioWeb.InsertarCargamentoRequest();
            inValue.Body = new Gen2_3Capas.ServicioWeb.InsertarCargamentoRequestBody();
            inValue.Body.IdRuta = IdRuta;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Peso = Peso;
            Gen2_3Capas.ServicioWeb.InsertarCargamentoResponse retVal = ((Gen2_3Capas.ServicioWeb.WSRutasSoap)(this)).InsertarCargamento(inValue);
            return retVal.Body.InsertarCargamentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gen2_3Capas.ServicioWeb.InsertarCargamentoResponse> Gen2_3Capas.ServicioWeb.WSRutasSoap.InsertarCargamentoAsync(Gen2_3Capas.ServicioWeb.InsertarCargamentoRequest request) {
            return base.Channel.InsertarCargamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gen2_3Capas.ServicioWeb.InsertarCargamentoResponse> InsertarCargamentoAsync(long IdRuta, string Descripcion, double Peso) {
            Gen2_3Capas.ServicioWeb.InsertarCargamentoRequest inValue = new Gen2_3Capas.ServicioWeb.InsertarCargamentoRequest();
            inValue.Body = new Gen2_3Capas.ServicioWeb.InsertarCargamentoRequestBody();
            inValue.Body.IdRuta = IdRuta;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Peso = Peso;
            return ((Gen2_3Capas.ServicioWeb.WSRutasSoap)(this)).InsertarCargamentoAsync(inValue);
        }
    }
}
